server:
  port: 8081
  servlet:
    context-path: /api/adapter
    application-display-name: model-adapter

spring:
  application:
    name: ${server.servlet.application-display-name}
  codec:
    max-in-memory-size: 4MB
  profiles:
    include: common,mq
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        use-new-id-generator-mappings: false
        format_sql: true
        show_sql: true
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always